name: Check WA DOR Guidance Updates

on:
  schedule:
    # Run every Monday at 9am PT (5pm UTC)
    - cron: '0 17 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check for guidance updates
        id: check
        run: |
          echo "Checking WA DOR website for updates..."
          # This is a placeholder - you'll customize this to actually check the website
          # For now, it just creates an issue to manually review
          echo "checked=true" >> $GITHUB_OUTPUT

      - name: Create issue if updates might be available
        if: steps.check.outputs.checked == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Check if there's already an open issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'guidance-update-check'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🔍 Weekly Check: Review WA DOR Guidance for Updates',
                labels: ['guidance-update-check', 'maintenance'],
                body: `## Weekly Guidance Update Check
                
                This is your weekly reminder to check if Washington Department of Revenue has released any updates to ESSB 5814 interim guidance.
                
                ### Where to Check:
                - [WA DOR Digital Products & Services](https://dor.wa.gov/taxes-rates/other-taxes/digital-products-and-services)
                - [WA DOR ESSB 5814 Resources](https://dor.wa.gov/about/legislative-priorities/essb-5814)
                
                ### What to Do:
                1. Visit the URLs above and check for any updated guidance documents
                2. If updates are found:
                   - Update the corresponding \`.txt\` files in \`guidance/wa-guidance/\`
                   - Update \`guidance/metadata.json\` with new dates
                   - Bump package version (use \`npm version patch\`)
                   - Commit changes: \`git commit -am "Update [category] guidance - [date]"\`
                   - Publish: \`npm publish\`
                3. Close this issue once checked (even if no updates)
                
                ### Current Version: 
                Check \`guidance/metadata.json\` for last update dates.
                
                ---
                *This issue is automatically created weekly to help maintain accurate guidance.*`
              });
            }

